version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  server:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      ADMIN_SECRET: "${ADMIN_SECRET}"
      POSTGRES_HOST: db
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      BASE_URL: "${BASE_URL}"
